sudo: false

language: python

python:
  - 3.5
  - 3.6

branches:
  only:
    - master
    - develop

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=kenchi setup.py test

after_success:
  - coveralls
