branches:
  only:
    - master

notifications:
  email: false

language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 3.6
#     - os: linux
#       sudo: false
#       python: 3.7-dev
#     - os: osx
#       sudo: false
#       python: 3.6
#     - os: osx
#       sudo: false
#       python: 3.7-dev

install:
  - pip install --upgrade pip setuptools
  - pip install coveralls
  - pip install .[develop]

script:
  - coverage run --source=kenchi setup.py test

after_success:
  - coveralls
