language: python

python:
  - 3.5

install:
  - pip install coveralls
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn

script:
  - coverage run --source=kenchi setup.py test

after_scipt:
  - coveralls
