sudo: false

language: python

python:
  - 3.5
  - 3.6

branches:
  only:
    - master
    - develop

install:
  - pip install coveralls
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn

script:
  - coverage run --source=kenchi setup.py test

after_success:
  - coveralls
