branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
#     - PYTHON: "C:\\Python37"
#     - PYTHON: "C:\\Python37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip setuptools"
  - "python -m pip install wheel"
  - "python -m pip install -r requirements.txt"

build: off

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
