package:
  name: kenchi
  version: "0.9.0"

source:
  git_rev: 0.9.0
  git_url: https://github.com/HazureChi/Kenchi.git

requirements:
  build:
    - python
    - matplotlib
    - networkx
    - numpy
    - scikit-learn
    - scipy
    - nose
  run:
    - python
    - matplotlib
    - networkx
    - numpy
    - scikit-learn
    - scipy
    - nose

test:
  imports:
    - kenchi

about:
  home: https://github.com/HazureChi/Kenchi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: http://kenchi.rtfd.io/
