package:
  name: kenchi
  version: "0.6.0"

source:
  git_rev: 0.6.0
  git_url: https://github.com/Y-oHr-N/kenchi.git

requirements:
  build:
    - python
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
  run:
    - python
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - kenchi

about:
  home: https://github.com/Y-oHr-N/kenchi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: http://kenchi.readthedocs.io/
